# Pandas: Basics (The Beatles)

*Pandas is a Python library for creating and manipulating DataFrames — two-dimensional objects designed to store data.*

Key capabilities:
- High-performance manipulation of text, integers, numbers, and dates
- Data alignment, reshaping, and pivoting
- Intelligent slicing, grouping, and subsetting
- Merging and joining of sets
- Integrated modules for analysis, plots, visualizations, maps, and networks

Resources:
- Official Pandas [documentation](https://pandas.pydata.org/about/)
- Tutorials at [W3Schools](https://www.w3schools.com/python/pandas/default.asp)
- A helpful [Pandas Cheat Sheet](https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf)

**Contents**
1. Introduction to DataFrames
2. Working with Rows
3. Working with Columns
4. Sort and Count
5. Combining and Merging DataFrames
6. Making the Most of Pandas

## 1. Introduction to DataFrames

Pandas **DataFrames** are the basic unit upon which all operations take place. Think of them as spreadsheets: rows of records and named columns.

Pandas can import (and export) data in many formats — **CSV** (comma separated values), **Excel**, **JSON** (JavaScript Object Notation, similar to a Python dictionary), and more.

### Import the Pandas Library

By convention, Pandas is imported under the short name `pd`.

In [1]:
import pandas as pd

### Meet the Beatles

Our case study is a dataset about the songs of the Beatles. It brings together two sources in a single CSV file:

- **Spotify** data: album, popularity, duration, and the acoustic ratings Spotify uses to characterize tracks (`Valence`, `Danceability`, `Energy`, `Acousticness`, and so on).
- **University of Belgrade (Serbia)** data: year, songwriter(s), lead singer(s), genre, styles, moods, and standing in various "Top 50" charts (Billboard, Rolling Stone, NME, and others).

We give the file path a name (simply for convenience), then pass that name to `pd.read_csv()` and name the resulting DataFrame.

In [2]:
beatles_csv = 'Beatles_Belgrade_Complete.csv'

beatles = pd.read_csv(beatles_csv)

### Inspect the DataFrame

A few essential methods for getting to know a new DataFrame:

| Method / Attribute | What it shows |
|--------------------|---------------|
| `df.head(n)` | First `n` rows (default 5) |
| `df.info()` | Column names, non-null counts, and data types |
| `df.shape` | Number of (rows, columns) — note: no `()` |
| `df.describe()` | Count, mean, standard deviation, min/max, and percentiles for numeric columns |

The left-hand column is the **index**, which begins with 0.

In [3]:
beatles.head(15)  # Shows the first 15 rows

,URI,Title,Year,Album,Popularity,Duration,Key,Mode,Tempo,Time_signature,...,Weeks at No1 in UK (The Guardian),Highest position (Billboard),Weeks at No1 (Billboard),Top 50 (Billboard),Top 50 (Ultimate classic rock),Top 50 (Rolling Stone),Top 50 (NME),Top 50 (Top50songs.org),"Top 50 (USA today, 2017)","Top 50 (Vulture, by Bill Wyman)"
0,spotify:track:2FDEHIMkjxFLzj688M2I3h,(You're So Square) Baby I Don't Care - Studio Jam,NaN,The Beatles,29.0,43.0,9.0,1.0,112.173,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,spotify:track:2HvTGx5fzFGpHSyRNvXd9T,12-bar Original,1965,Anthology 2,31.0,175.0,9.0,1.0,122.678,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,spotify:track:34dsKRJHIadrrNdCDtMwGn,A Beginning - Anthology 3 Version,NaN,Anthology 3,29.0,50.0,0.0,1.0,90.588,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,spotify:track:0hKRSZhUGEhKU6aNSPBACZ,A Day in the Life,1967,Sgt. Pepper's Lonely Hearts Club Band,65.0,335.0,4.0,0.0,163.219,4.0,...,NaN,NaN,NaN,NaN,1.0,1.0,2.0,18.0,1.0,1.0
4,spotify:track:5J2CHimS7dWYMImCHkEFaJ,A Hard Day's Night,1964,A Hard Day's Night,71.0,152.0,0.0,1.0,138.514,4.0,...,3.0,1.0,2.0,8.0,18.0,11.0,19.0,19.0,15.0,41.0
5,spotify:track:5RuE7nwp4TWsRvLXG7Yjy1,A Shot of Rhythm and Blues,1963,Live at the BBC,35.0,136.0,2.0,1.0,128.919,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,spotify:track:7fh53ta3vAOGJMQ4i5tCHe,A Taste of Honey,1963,Please Please Me,51.0,163.0,1.0,0.0,101.408,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,spotify:track:4dkoqJrP0L8FXftrMZongF,Across the Universe,1968,Let It Be,69.0,230.0,1.0,1.0,152.126,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,7.0,30.0,32.0,NaN
8,spotify:track:00fyPXxe2SCBHnFwEO9Eh1,Across the Universe - Take 2 / Anthology 2 Ver...,NaN,Anthology 2,35.0,212.0,2.0,1.0,79.377,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,spotify:track:0IxxqsYBcCHEQ1HqLYJnwx,Act Naturally,1965,Help!,52.0,139.0,7.0,1.0,93.020,4.0,...,NaN,47.0,NaN,50.0,NaN,NaN,NaN,NaN,NaN,NaN
10,spotify:track:3OUpVpFeNx5jeInhHqiNfs,Ain't She Sweet,1961,Anthology 1,38.0,133.0,4.0,1.0,77.967,4.0,...,NaN,19.0,NaN,41.0,NaN,NaN,NaN,NaN,NaN,NaN
11,spotify:track:5tztLBvTlNC15Np2tnQ5Ll,All I've Got to Do,1963,With the Beatles,55.0,124.0,1.0,0.0,119.403,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,spotify:track:4joiWvli4qJVEW6qZV2i2J,All My Loving,1963,With the Beatles,73.0,124.0,1.0,0.0,77.560,4.0,...,NaN,NaN,NaN,NaN,46.0,44.0,35.0,43.0,29.0,NaN
13,spotify:track:25RYJGPnetSkV8le7TeJnR,All Things Must Pass,1969,Anthology 3,35.0,185.0,9.0,1.0,93.232,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,spotify:track:2ck8lFrYAch2GPtdhpTHe3,All Together Now,1967,Yellow Submarine,45.0,130.0,2.0,1.0,95.937,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
beatles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 285 entries, 0 to 284
Data columns (total 45 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   URI                                  285 non-null    object
 1   Title                                285 non-null    object
 2   Year                                 277 non-null    object
 3   Album                                284 non-null    object
 4   Popularity                           285 non-null    float64
 5   Duration                             285 non-null    float64
 6   Key                                  285 non-null    float64
 7   Mode                                 285 non-null    float64
 8   Tempo                                285 non-null    float64
 9   Time_signature                       285 non-null    float64
 10  Valence                              285 non-null    float64
 11  Danceability                         285 non-null    float64
 12  Energy                               285 non-null    float64
 13  Loudness                             285 non-null    float64
 14  Acousticness                         285 non-null    float64
 15  Instrumentalness                     285 non-null    float64
 16  Liveness                             285 non-null    float64
 17  Speechiness                          285 non-null    float64
 18  Album debut                          275 non-null    object
 19  Other releases                       213 non-null    float64
 20  Single A side                        90 non-null     object
 21  Single B side                        90 non-null     object
 22  Single certification                 50 non-null     object
 23  Genre                                278 non-null    object
 24  Styles                               257 non-null    object
 25  Themes                               184 non-null    object
 26  Moods                                260 non-null    object
 27  Songwriter(s)                        278 non-null    object
 28  Lead vocal(s)                        273 non-null    object
 29  Cover                                66 non-null     object
 30  Covered by                           182 non-null    float64
 31  Chart position UK (Wikipedia)        45 non-null     float64
 32  Chart position US (Wikipedia)        67 non-null     float64
 33  Highest position (The Guardian)      31 non-null     float64
 34  Weeks on chart in UK (The Guardian)  31 non-null     float64
 35  Weeks at No1 in UK (The Guardian)    16 non-null     float64
 36  Highest position (Billboard)         49 non-null     float64
 37  Weeks at No1 (Billboard)             15 non-null     float64
 38  Top 50 (Billboard)                   49 non-null     float64
 39  Top 50 (Ultimate classic rock)       49 non-null     float64
 40  Top 50 (Rolling Stone)               49 non-null     float64
 41  Top 50 (NME)                         49 non-null     float64
 42  Top 50 (Top50songs.org)              50 non-null     float64
 43  Top 50 (USA today, 2017)             50 non-null     float64
 44  Top 50 (Vulture, by Bill Wyman)      42 non-null     float64
dtypes: float64(30), object(15)
memory usage: 100.3+ KB

In [5]:
# .shape is an attribute, not a method, so there are no ()
beatles.shape

(285, 45)

In [6]:
# describe() is a method, so we need to use ().  
# This method provides a summary of the numerical columns in the DataFrame, including count, mean, standard deviation, min, max, and quartiles.
# NB:  This is probably of limited value for categorical data, but it can still be useful for understanding the distribution of numerical data in the dataset.
beatles.describe()

,Popularity,Duration,Key,Mode,Tempo,Time_signature,Valence,Danceability,Energy,Loudness,...,Weeks at No1 in UK (The Guardian),Highest position (Billboard),Weeks at No1 (Billboard),Top 50 (Billboard),Top 50 (Ultimate classic rock),Top 50 (Rolling Stone),Top 50 (NME),Top 50 (Top50songs.org),"Top 50 (USA today, 2017)","Top 50 (Vulture, by Bill Wyman)"
count,285.000000,285.000000,285.000000,285.000000,285.000000,285.000000,285.000000,285.000000,285.000000,285.000000,...,16.000000,49.000000,15.000000,49.000000,49.000000,49.000000,49.000000,50.00000,50.00000,42.000000
mean,50.087719,158.407018,4.961404,0.856140,121.348589,3.859649,0.692141,0.528540,0.570684,-9.737979,...,4.125000,8.877551,3.600000,25.306122,25.959184,25.551020,25.693878,25.50000,25.50000,25.500000
std,14.415466,57.361001,3.387308,0.351565,28.525083,0.461115,0.234652,0.131461,0.189290,2.426773,...,1.746425,11.598550,2.097618,14.663168,14.358446,14.723933,14.666010,14.57738,14.57738,15.904057
min,22.000000,23.000000,0.000000,0.000000,59.004000,1.000000,0.033000,0.146000,0.079600,-23.030000,...,2.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.00000,1.000000
25%,39.000000,128.000000,2.000000,1.000000,97.871000,4.000000,0.553000,0.440000,0.457000,-11.097000,...,3.000000,1.000000,2.000000,13.000000,14.000000,13.000000,13.000000,13.25000,13.25000,11.250000
50%,52.000000,149.000000,4.000000,1.000000,123.227000,4.000000,0.735000,0.538000,0.571000,-9.435000,...,3.500000,3.000000,3.000000,25.000000,26.000000,26.000000,26.000000,25.50000,25.50000,25.500000
75%,59.000000,175.000000,9.000000,1.000000,137.717000,4.000000,0.886000,0.629000,0.724000,-8.178000,...,5.250000,12.000000,4.500000,38.000000,38.000000,38.000000,38.000000,37.75000,37.75000,39.750000
max,87.000000,502.000000,11.000000,1.000000,209.242000,5.000000,0.979000,0.880000,0.983000,-5.690000,...,7.000000,47.000000,9.000000,50.000000,50.000000,50.000000,50.000000,50.00000,50.00000,50.000000

## 2. Working with Rows

By default Pandas shows only the first and last five rows of a large DataFrame. Here are your options:

| Method | What it does |
|--------|-------------|
| `df.head(n)` | First `n` rows (default 5) |
| `df.tail(n)` | Last `n` rows (default 5) |
| `df.sample(n)` | Random sample of `n` rows (default 1) |
| `pd.set_option('display.max_rows', None)` | Show **all** rows when the frame is displayed |

In [7]:
beatles.tail(10)
# beatles.sample(10)

,URI,Title,Year,Album,Popularity,Duration,Key,Mode,Tempo,Time_signature,...,Weeks at No1 in UK (The Guardian),Highest position (Billboard),Weeks at No1 (Billboard),Top 50 (Billboard),Top 50 (Ultimate classic rock),Top 50 (Rolling Stone),Top 50 (NME),Top 50 (Top50songs.org),"Top 50 (USA today, 2017)","Top 50 (Vulture, by Bill Wyman)"
275,spotify:track:1n8oABN9yti0owTEKcms0q,You Know What to Do,1964,Anthology 1,28.0,119.0,9.0,1.0,82.770,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
276,spotify:track:0y1LLH0NiwOD5tM3aNMXTr,You Like Me Too Much,1965,Help!,50.0,155.0,7.0,1.0,88.316,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
277,spotify:track:1jOLTO379yIu9aMnCkpMQl,You Never Give Me Your Money,1969,Abbey Road,60.0,242.0,0.0,1.0,174.464,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278,spotify:track:4LLBKnNCrSRrSjSTuiwjE9,You Won't See Me,1965,Rubber Soul,57.0,202.0,9.0,1.0,115.941,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
279,spotify:track:175jiRVJ6N6ayJQ1FXim56,You'll Be Mine,1960,Anthology 1,28.0,99.0,5.0,1.0,89.585,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
280,spotify:track:70HNt0eoBVqr4ss68U8x3B,You're Going to Lose That Girl,1965,Help!,57.0,140.0,4.0,1.0,131.975,4.0,...,NaN,NaN,NaN,NaN,NaN,27.0,NaN,NaN,NaN,NaN
281,spotify:track:4F1AgKpuFRMLEgtPETVwZk,You've Got to Hide Your Love Away,1965,Help!,73.0,131.0,7.0,1.0,184.267,3.0,...,NaN,NaN,NaN,NaN,42.0,31.0,49.0,NaN,37.0,46.0
282,spotify:track:7rgUYidQh5tH0YlXCoKaYJ,You've Really Got a Hold on Me,1963,With the Beatles,54.0,182.0,9.0,1.0,77.643,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
283,spotify:track:3FuRBetiFz4ijeLdGCxQ5Y,Young Blood,1963,Live at the BBC,29.0,116.0,2.0,1.0,68.111,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
284,spotify:track:1dxbAIfCASqv6jix2R1Taj,Your Mother Should Know,1967,Magical Mystery Tour,58.0,149.0,0.0,1.0,117.613,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Selecting Rows: `iloc` and `loc`

`df.iloc` and `df.loc` are *not* the same!

#### `iloc` — select by **integer index position**

Syntax: `df.iloc[start_row : end_row, start_col : end_col]`

- Square brackets `[ ]` indicate that we are taking a *slice* (a section) of the DataFrame.
- The first number is *inclusive* and the second is *exclusive*: `iloc[10:15]` gives rows 10, 11, 12, 13, 14 — but *not* row 15.
- Omit the first number to start at the beginning; omit the last to go to the end. Omit the column range to get all columns.

In [8]:
# Rows 10–14, all columns
beatles.iloc[10:15]

,URI,Title,Year,Album,Popularity,Duration,Key,Mode,Tempo,Time_signature,...,Weeks at No1 in UK (The Guardian),Highest position (Billboard),Weeks at No1 (Billboard),Top 50 (Billboard),Top 50 (Ultimate classic rock),Top 50 (Rolling Stone),Top 50 (NME),Top 50 (Top50songs.org),"Top 50 (USA today, 2017)","Top 50 (Vulture, by Bill Wyman)"
10,spotify:track:3OUpVpFeNx5jeInhHqiNfs,Ain't She Sweet,1961,Anthology 1,38.0,133.0,4.0,1.0,77.967,4.0,...,NaN,19.0,NaN,41.0,NaN,NaN,NaN,NaN,NaN,NaN
11,spotify:track:5tztLBvTlNC15Np2tnQ5Ll,All I've Got to Do,1963,With the Beatles,55.0,124.0,1.0,0.0,119.403,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,spotify:track:4joiWvli4qJVEW6qZV2i2J,All My Loving,1963,With the Beatles,73.0,124.0,1.0,0.0,77.560,4.0,...,NaN,NaN,NaN,NaN,46.0,44.0,35.0,43.0,29.0,NaN
13,spotify:track:25RYJGPnetSkV8le7TeJnR,All Things Must Pass,1969,Anthology 3,35.0,185.0,9.0,1.0,93.232,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,spotify:track:2ck8lFrYAch2GPtdhpTHe3,All Together Now,1967,Yellow Submarine,45.0,130.0,2.0,1.0,95.937,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
# Rows 10–14, columns 1–3 (Title, Year, Album)
beatles.iloc[10:15, 1:4]

                   Title  Year             Album
10       Ain't She Sweet  1961       Anthology 1
11    All I've Got to Do  1963  With the Beatles
12         All My Loving  1963  With the Beatles
13  All Things Must Pass  1969       Anthology 3
14      All Together Now  1967  Yellow Submarine

#### `loc` — select by **label**

`loc` selects rows by the *label* in the index. With the default numeric index, labels and positions look the same. `loc` really becomes useful when the index is made of strings — for instance, if we make the song `Title` the index with `set_index()`:

In [10]:

# here we are using the Title column as the index
# this allows us to access rows by their title rather than by their integer position

# note that this does not change the original DataFrame
# it just creates a new one with the index set to the Title column
beatles_by_title = beatles.set_index('Title')

In [11]:
# this returns the unique row that matches the index value 'Yesterday'
# it will look like a DataFrame, but it is actually a Series because there is only one row

beatles_by_title.loc['Yesterday']

URI                                                 spotify:track:3BQHpFgAp4l80e1XslIjNI
Year                                                                                1965
Album                                                                              Help!
Popularity                                                                          80.0
Duration                                                                           123.0
Key                                                                                  5.0
Mode                                                                                 1.0
Tempo                                                                             96.529
Time_signature                                                                       4.0
Valence                                                                            0.315
Danceability                                                                       0.332
Energy                                                                             0.179
Loudness                                                                          -11.83
Acousticness                                                                       0.879
Instrumentalness                                                                     0.0
Liveness                                                                          0.0886
Speechiness                                                                       0.0326
Album debut                                            UK: Help! US: Yesterday and Today
Other releases                                                                      33.0
Single A side                                                                  Yesterday
Single B side                                                              Act Naturally
Single certification                                                           RIAA Gold
Genre                                                              Baroque Pop, Pop/Rock
Styles                                 British Invasion, Contemporary Pop/Rock, Early...
Themes                                                  Breakup, Feeling Blue, Heartache
Moods                                  Bittersweet Earnest Plaintive Poignant Reflect...
Songwriter(s)                                                                  McCartney
Lead vocal(s)                                                                  McCartney
Cover                                                                                NaN
Covered by                                                                          70.0
Chart position UK (Wikipedia)                                                        8.0
Chart position US (Wikipedia)                                                        1.0
Highest position (The Guardian)                                                      8.0
Weeks on chart in UK (The Guardian)                                                  7.0
Weeks at No1 in UK (The Guardian)                                                    NaN
Highest position (Billboard)                                                         1.0
Weeks at No1 (Billboard)                                                             4.0
Top 50 (Billboard)                                                                  12.0
Top 50 (Ultimate classic rock)                                                      12.0
Top 50 (Rolling Stone)                                                               4.0
Top 50 (NME)                                                                        22.0
Top 50 (Top50songs.org)                                                              3.0
Top 50 (USA today, 2017)                                                             6.0
Top 50 (Vulture, by Bill Wyman)                                                     39.0
Name: Yesterday, dtype: object

In [12]:
# Several songs at once, and only the columns we name
# first the lists
song_list = ['Help!', 'Hey Jude', 'Let It Be']
column_list = ['Year', 'Album', 'Lead vocal(s)']   

# now we pass the lists to the .loc[] method to get the rows and columns we want
# in this case 'loc' is taking two arguments: 
# the first is the list of songs, and the second is the list of columns
beatles_by_title.loc[song_list, column_list]

           Year                                    Album Lead vocal(s)
Title
Help!      1965                                    Help!        Lennon
Hey Jude   1968  Past Masters (Vols. 1 & 2 / Remastered)     McCartney
Let It Be  1969                                Let It Be     McCartney

### Dropping Rows

You can remove ("drop") rows by referring to their index numbers. Here we drop rows 0, 2, and 8, which are alternate takes and studio jams.

Your DataFrame will then be missing those index numbers. Use `.reset_index(drop=True)` to make the index continuous again (0 to the end).

In [13]:
beatles_trimmed = beatles.drop([0, 2, 8])
beatles_trimmed = beatles_trimmed.reset_index(drop=True)
beatles_trimmed.head(10)

,URI,Title,Year,Album,Popularity,Duration,Key,Mode,Tempo,Time_signature,...,Weeks at No1 in UK (The Guardian),Highest position (Billboard),Weeks at No1 (Billboard),Top 50 (Billboard),Top 50 (Ultimate classic rock),Top 50 (Rolling Stone),Top 50 (NME),Top 50 (Top50songs.org),"Top 50 (USA today, 2017)","Top 50 (Vulture, by Bill Wyman)"
0,spotify:track:2HvTGx5fzFGpHSyRNvXd9T,12-bar Original,1965,Anthology 2,31.0,175.0,9.0,1.0,122.678,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,spotify:track:0hKRSZhUGEhKU6aNSPBACZ,A Day in the Life,1967,Sgt. Pepper's Lonely Hearts Club Band,65.0,335.0,4.0,0.0,163.219,4.0,...,NaN,NaN,NaN,NaN,1.0,1.0,2.0,18.0,1.0,1.0
2,spotify:track:5J2CHimS7dWYMImCHkEFaJ,A Hard Day's Night,1964,A Hard Day's Night,71.0,152.0,0.0,1.0,138.514,4.0,...,3.0,1.0,2.0,8.0,18.0,11.0,19.0,19.0,15.0,41.0
3,spotify:track:5RuE7nwp4TWsRvLXG7Yjy1,A Shot of Rhythm and Blues,1963,Live at the BBC,35.0,136.0,2.0,1.0,128.919,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,spotify:track:7fh53ta3vAOGJMQ4i5tCHe,A Taste of Honey,1963,Please Please Me,51.0,163.0,1.0,0.0,101.408,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,spotify:track:4dkoqJrP0L8FXftrMZongF,Across the Universe,1968,Let It Be,69.0,230.0,1.0,1.0,152.126,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,7.0,30.0,32.0,NaN
6,spotify:track:0IxxqsYBcCHEQ1HqLYJnwx,Act Naturally,1965,Help!,52.0,139.0,7.0,1.0,93.020,4.0,...,NaN,47.0,NaN,50.0,NaN,NaN,NaN,NaN,NaN,NaN
7,spotify:track:3OUpVpFeNx5jeInhHqiNfs,Ain't She Sweet,1961,Anthology 1,38.0,133.0,4.0,1.0,77.967,4.0,...,NaN,19.0,NaN,41.0,NaN,NaN,NaN,NaN,NaN,NaN
8,spotify:track:5tztLBvTlNC15Np2tnQ5Ll,All I've Got to Do,1963,With the Beatles,55.0,124.0,1.0,0.0,119.403,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,spotify:track:4joiWvli4qJVEW6qZV2i2J,All My Loving,1963,With the Beatles,73.0,124.0,1.0,0.0,77.560,4.0,...,NaN,NaN,NaN,NaN,46.0,44.0,35.0,43.0,29.0,NaN

## 3. Working with Columns

| # | Task |
|---|------|
| 1 | Select columns by position with `iloc` |
| 2 | Show all column names |
| 3 | Add a column |
| 4 | Drop a column |
| 5 | Rename a column (or columns) |
| 6 | Show column data types |
| 7 | Reorder or subset columns |

### Select Columns with `iloc`

The same `iloc` syntax works for columns: rows come first, then columns. Use `:` for "all rows".

Want to count from the *end*? `-1` is the *last* column.

In [14]:
# All rows, first five columns (0 through 4)
beatles.iloc[:, 0:5]

,URI,Title,Year,Album,Popularity
0,spotify:track:2FDEHIMkjxFLzj688M2I3h,(You're So Square) Baby I Don't Care - Studio Jam,NaN,The Beatles,29.0
1,spotify:track:2HvTGx5fzFGpHSyRNvXd9T,12-bar Original,1965,Anthology 2,31.0
2,spotify:track:34dsKRJHIadrrNdCDtMwGn,A Beginning - Anthology 3 Version,NaN,Anthology 3,29.0
3,spotify:track:0hKRSZhUGEhKU6aNSPBACZ,A Day in the Life,1967,Sgt. Pepper's Lonely Hearts Club Band,65.0
4,spotify:track:5J2CHimS7dWYMImCHkEFaJ,A Hard Day's Night,1964,A Hard Day's Night,71.0
...,...,...,...,...,...
280,spotify:track:70HNt0eoBVqr4ss68U8x3B,You're Going to Lose That Girl,1965,Help!,57.0
281,spotify:track:4F1AgKpuFRMLEgtPETVwZk,You've Got to Hide Your Love Away,1965,Help!,73.0
282,spotify:track:7rgUYidQh5tH0YlXCoKaYJ,You've Really Got a Hold on Me,1963,With the Beatles,54.0
283,spotify:track:3FuRBetiFz4ijeLdGCxQ5Y,Young Blood,1963,Live at the BBC,29.0
284,spotify:track:1dxbAIfCASqv6jix2R1Taj,Your Mother Should Know,1967,Magical Mystery Tour,58.0

In [15]:
# All rows, last column only
beatles.iloc[:, -1]

0       NaN
1       NaN
2       NaN
3       1.0
4      41.0
       ...
280     NaN
281    46.0
282     NaN
283     NaN
284     NaN
Name: Top 50 (Vulture, by Bill Wyman), Length: 285, dtype: float64

### Show All Column Names

Note the absence of `()` — `.columns` is an attribute, not a method.

In [16]:
beatles.columns

Index(['URI', 'Title', 'Year', 'Album', 'Popularity', 'Duration', 'Key',
       'Mode', 'Tempo', 'Time_signature', 'Valence', 'Danceability', 'Energy',
       'Loudness', 'Acousticness', 'Instrumentalness', 'Liveness',
       'Speechiness', 'Album debut', 'Other releases', 'Single A side',
       'Single B side', 'Single certification', 'Genre', 'Styles', 'Themes',
       'Moods', 'Songwriter(s)', 'Lead vocal(s)', 'Cover', 'Covered by',
       'Chart position UK (Wikipedia)', 'Chart position US (Wikipedia)',
       'Highest position (The Guardian)',
       'Weeks on chart in UK (The Guardian)',
       'Weeks at No1 in UK (The Guardian)', 'Highest position (Billboard)',
       'Weeks at No1 (Billboard)', 'Top 50 (Billboard)',
       'Top 50 (Ultimate classic rock)', 'Top 50 (Rolling Stone)',
       'Top 50 (NME)', 'Top 50 (Top50songs.org)', 'Top 50 (USA today, 2017)',
       'Top 50 (Vulture, by Bill Wyman)'],
      dtype='object')

In [17]:
# Sorted alphabetically
beatles.columns.sort_values()

Index(['Acousticness', 'Album', 'Album debut', 'Chart position UK (Wikipedia)',
       'Chart position US (Wikipedia)', 'Cover', 'Covered by', 'Danceability',
       'Duration', 'Energy', 'Genre', 'Highest position (Billboard)',
       'Highest position (The Guardian)', 'Instrumentalness', 'Key',
       'Lead vocal(s)', 'Liveness', 'Loudness', 'Mode', 'Moods',
       'Other releases', 'Popularity', 'Single A side', 'Single B side',
       'Single certification', 'Songwriter(s)', 'Speechiness', 'Styles',
       'Tempo', 'Themes', 'Time_signature', 'Title', 'Top 50 (Billboard)',
       'Top 50 (NME)', 'Top 50 (Rolling Stone)', 'Top 50 (Top50songs.org)',
       'Top 50 (USA today, 2017)', 'Top 50 (Ultimate classic rock)',
       'Top 50 (Vulture, by Bill Wyman)', 'URI', 'Valence',
       'Weeks at No1 (Billboard)', 'Weeks at No1 in UK (The Guardian)',
       'Weeks on chart in UK (The Guardian)', 'Year'],
      dtype='object')

### Add a Column

Assign a new column name to an expression that is evaluated for every row.

Here we create a column `'sad'`. If a song's Spotify `Valence` (musical "positiveness") is less than 0.2, `'sad'` will be `True`; otherwise it will be `False`.

NB:  later we will learn how to use **fitler** the results so we see only the sad songs.

In [18]:
beatles['sad'] = beatles['Valence'] < 0.2
beatles[['Title', 'Valence', 'sad']].head(10)

                                               Title  Valence    sad
0  (You're So Square) Baby I Don't Care - Studio Jam    0.353  False
1                                    12-bar Original    0.566  False
2                  A Beginning - Anthology 3 Version    0.033   True
3                                  A Day in the Life    0.175   True
4                                 A Hard Day's Night    0.797  False
5                         A Shot of Rhythm and Blues    0.968  False
6                                   A Taste of Honey    0.412  False
7                                Across the Universe    0.858  False
8  Across the Universe - Take 2 / Anthology 2 Ver...    0.463  False
9                                      Act Naturally    0.944  False

### Drop a Column

Columns to drop must be passed as a **list**, even if there is only one. Here we drop the Spotify `URI` column, which we won't need.

NB:  if you have already dropped a column, you may need to restart the kernel and re-run the notebook to get it back.  And if you rerun the same cell after you have dropped the column, you will get an error because the column is no longer there!

In [19]:


beatles = beatles.drop(columns=['URI']) # notice that the 'URI' column name is square brackets!
beatles.columns

Index(['Title', 'Year', 'Album', 'Popularity', 'Duration', 'Key', 'Mode',
       'Tempo', 'Time_signature', 'Valence', 'Danceability', 'Energy',
       'Loudness', 'Acousticness', 'Instrumentalness', 'Liveness',
       'Speechiness', 'Album debut', 'Other releases', 'Single A side',
       'Single B side', 'Single certification', 'Genre', 'Styles', 'Themes',
       'Moods', 'Songwriter(s)', 'Lead vocal(s)', 'Cover', 'Covered by',
       'Chart position UK (Wikipedia)', 'Chart position US (Wikipedia)',
       'Highest position (The Guardian)',
       'Weeks on chart in UK (The Guardian)',
       'Weeks at No1 in UK (The Guardian)', 'Highest position (Billboard)',
       'Weeks at No1 (Billboard)', 'Top 50 (Billboard)',
       'Top 50 (Ultimate classic rock)', 'Top 50 (Rolling Stone)',
       'Top 50 (NME)', 'Top 50 (Top50songs.org)', 'Top 50 (USA today, 2017)',
       'Top 50 (Vulture, by Bill Wyman)', 'sad'],
      dtype='object')

### Rename Columns

Several column names in this dataset contain spaces and punctuation, like `'Album debut'` and `'Songwriter(s)'`. They work, but they are awkward to type. It is good practice to use short names without spaces or special characters.

**Option 1** — copy-then-drop (useful for a single column):

In [20]:
# Copy 'Album debut' to a new 'album_debut' column, then drop the original
beatles['album_debut'] = beatles['Album debut']

# here we drop the original 'Album debut' column, which we no longer need
beatles = beatles.drop(columns=['Album debut'])
beatles.columns

Index(['Title', 'Year', 'Album', 'Popularity', 'Duration', 'Key', 'Mode',
       'Tempo', 'Time_signature', 'Valence', 'Danceability', 'Energy',
       'Loudness', 'Acousticness', 'Instrumentalness', 'Liveness',
       'Speechiness', 'Other releases', 'Single A side', 'Single B side',
       'Single certification', 'Genre', 'Styles', 'Themes', 'Moods',
       'Songwriter(s)', 'Lead vocal(s)', 'Cover', 'Covered by',
       'Chart position UK (Wikipedia)', 'Chart position US (Wikipedia)',
       'Highest position (The Guardian)',
       'Weeks on chart in UK (The Guardian)',
       'Weeks at No1 in UK (The Guardian)', 'Highest position (Billboard)',
       'Weeks at No1 (Billboard)', 'Top 50 (Billboard)',
       'Top 50 (Ultimate classic rock)', 'Top 50 (Rolling Stone)',
       'Top 50 (NME)', 'Top 50 (Top50songs.org)', 'Top 50 (USA today, 2017)',
       'Top 50 (Vulture, by Bill Wyman)', 'sad', 'album_debut'],
      dtype='object')

**Option 2** — rename with a dictionary (cleaner for several columns at once). Keys are the old names, and values are the new ones:

In [21]:
# dictionary has the OLD column names as KEYS and the NEW column names as VALUES

col_dict = {
    'Songwriter(s)': 'songwriter',
    'Lead vocal(s)': 'lead_vocal',
    'Top 50 (Billboard)': 'top_50_billboard'
}

# now we pass the dictionary to the rename() method to change the column names

beatles = beatles.rename(columns=col_dict)
beatles.columns

Index(['Title', 'Year', 'Album', 'Popularity', 'Duration', 'Key', 'Mode',
       'Tempo', 'Time_signature', 'Valence', 'Danceability', 'Energy',
       'Loudness', 'Acousticness', 'Instrumentalness', 'Liveness',
       'Speechiness', 'Other releases', 'Single A side', 'Single B side',
       'Single certification', 'Genre', 'Styles', 'Themes', 'Moods',
       'songwriter', 'lead_vocal', 'Cover', 'Covered by',
       'Chart position UK (Wikipedia)', 'Chart position US (Wikipedia)',
       'Highest position (The Guardian)',
       'Weeks on chart in UK (The Guardian)',
       'Weeks at No1 in UK (The Guardian)', 'Highest position (Billboard)',
       'Weeks at No1 (Billboard)', 'top_50_billboard',
       'Top 50 (Ultimate classic rock)', 'Top 50 (Rolling Stone)',
       'Top 50 (NME)', 'Top 50 (Top50songs.org)', 'Top 50 (USA today, 2017)',
       'Top 50 (Vulture, by Bill Wyman)', 'sad', 'album_debut'],
      dtype='object')

**Tip: `dict.fromkeys()` as a shortcut**

`dict.fromkeys()` makes a dictionary instantly, with the current column names as the keys and `None` as each value. Fill in only the names you want to change and delete the rest, then finish with `df.rename(columns=col_dict)`. This is handy when there are many columns.

NB:  You will ened to copy the output of col_dict into a cell in order to edit it.  You cannot edit the output of a cell directly.

In [22]:
col_dict = dict.fromkeys(beatles.columns)
col_dict

{'Title': None,
 'Year': None,
 'Album': None,
 'Popularity': None,
 'Duration': None,
 'Key': None,
 'Mode': None,
 'Tempo': None,
 'Time_signature': None,
 'Valence': None,
 'Danceability': None,
 'Energy': None,
 'Loudness': None,
 'Acousticness': None,
 'Instrumentalness': None,
 'Liveness': None,
 'Speechiness': None,
 'Other releases': None,
 'Single A side': None,
 'Single B side': None,
 'Single certification': None,
 'Genre': None,
 'Styles': None,
 'Themes': None,
 'Moods': None,
 'songwriter': None,
 'lead_vocal': None,
 'Cover': None,
 'Covered by': None,
 'Chart position UK (Wikipedia)': None,
 'Chart position US (Wikipedia)': None,
 'Highest position (The Guardian)': None,
 'Weeks on chart in UK (The Guardian)': None,
 'Weeks at No1 in UK (The Guardian)': None,
 'Highest position (Billboard)': None,
 'Weeks at No1 (Billboard)': None,
 'top_50_billboard': None,
 'Top 50 (Ultimate classic rock)': None,
 'Top 50 (Rolling Stone)': None,
 'Top 50 (NME)': None,
 'Top 50 (Top50songs.org)': None,
 'Top 50 (USA today, 2017)': None,
 'Top 50 (Vulture, by Bill Wyman)': None,
 'sad': None,
 'album_debut': None}

### Show Column Data Types

Each column has a **dtype**, which tells Pandas what form the column's data are in. This affects which operations are possible: you can't do math on a text column, and you can't use string methods on a numeric one.

Notice that `Year` is stored as text rather than a number. A few songs have entries like `'1977/1994'` (recorded in one year, released in another), so Pandas cannot treat the whole column as numbers. You will learn how to fix problems like this in the **Clean Data** notebook.

In [23]:
beatles.dtypes

Title                                   object
Year                                    object
Album                                   object
Popularity                             float64
Duration                               float64
Key                                    float64
Mode                                   float64
Tempo                                  float64
Time_signature                         float64
Valence                                float64
Danceability                           float64
Energy                                 float64
Loudness                               float64
Acousticness                           float64
Instrumentalness                       float64
Liveness                               float64
Speechiness                            float64
Other releases                         float64
Single A side                           object
Single B side                           object
Single certification                    object
Genre                                   object
Styles                                  object
Themes                                  object
Moods                                   object
songwriter                              object
lead_vocal                              object
Cover                                   object
Covered by                             float64
Chart position UK (Wikipedia)          float64
Chart position US (Wikipedia)          float64
Highest position (The Guardian)        float64
Weeks on chart in UK (The Guardian)    float64
Weeks at No1 in UK (The Guardian)      float64
Highest position (Billboard)           float64
Weeks at No1 (Billboard)               float64
top_50_billboard                       float64
Top 50 (Ultimate classic rock)         float64
Top 50 (Rolling Stone)                 float64
Top 50 (NME)                           float64
Top 50 (Top50songs.org)                float64
Top 50 (USA today, 2017)               float64
Top 50 (Vulture, by Bill Wyman)        float64
sad                                       bool
album_debut                             object
dtype: object

### Reorder Columns / Create a Subset

Pass a list of column names in the order you want. Leave out any column to exclude it. This is how you make a **new DataFrame with just a subset of columns**.

In [24]:
column_list = ['Title', 'Year', 'Album', 'Genre', 'songwriter', 'lead_vocal', 'top_50_billboard']
beatles_short = beatles[column_list]
beatles_short

,Title,Year,Album,Genre,songwriter,lead_vocal,top_50_billboard
0,(You're So Square) Baby I Don't Care - Studio Jam,NaN,The Beatles,NaN,NaN,NaN,NaN
1,12-bar Original,1965,Anthology 2,Blues,"Lennon, McCartney, Harrison and Starkey",NaN,NaN
2,A Beginning - Anthology 3 Version,NaN,Anthology 3,NaN,NaN,NaN,NaN
3,A Day in the Life,1967,Sgt. Pepper's Lonely Hearts Club Band,"Psychedelic Rock, Art Rock, Pop/Rock",Lennon and McCartney,Lennon and McCartney,NaN
4,A Hard Day's Night,1964,A Hard Day's Night,"Rock, Electronic, Pop/Rock",Lennon,"Lennon, with McCartney",8.0
...,...,...,...,...,...,...,...
280,You're Going to Lose That Girl,1965,Help!,"Rock, Pop/Rock",Lennon,Lennon,NaN
281,You've Got to Hide Your Love Away,1965,Help!,FolkPop/Rock,Lennon,Lennon,NaN
282,You've Really Got a Hold on Me,1963,With the Beatles,"Soul, Pop/Rock",Robinson,Lennon and Harrison,NaN
283,Young Blood,1963,Live at the BBC,Pop/Rock,"Leiber, Stoller",Harrison,NaN
284,Your Mother Should Know,1967,Magical Mystery Tour,"Music Hall, Vaudeville Rock, Psychedelic Pop, ...",McCartney,McCartney,NaN

### A Column is a Series

An individual column is called a **Series**, which has its own methods.

| Expression | What it returns |
|------------|----------------|
| `df["col"]` | The column as a Series |
| `df["col"].unique()` | Array of the unique values |
| `df["col"].nunique()` | *Number* of unique values |
| `df["col"].value_counts()` | Count of each unique value |

> You can also reference a column like this: `beatles.Album`. But this "dot" syntax does not work for column names with spaces or special characters, such as `beatles["Single A side"]`. That is another good reason to rename such columns. The examples here use the bracketed syntax.

In [30]:

# one column as a Series
beatles["Album"]

0                                The Beatles
1                                Anthology 2
2                                Anthology 3
3      Sgt. Pepper's Lonely Hearts Club Band
4                         A Hard Day's Night
                       ...
280                                    Help!
281                                    Help!
282                         With the Beatles
283                          Live at the BBC
284                     Magical Mystery Tour
Name: Album, Length: 285, dtype: object

In [31]:
# the unique values in that series
beatles["Album"].unique()

array(['The Beatles', 'Anthology 2', 'Anthology 3',
       "Sgt. Pepper's Lonely Hearts Club Band", "A Hard Day's Night",
       'Live at the BBC', 'Please Please Me', 'Let It Be', 'Help!',
       'Anthology 1', 'With the Beatles', 'Yellow Submarine',
       'Magical Mystery Tour', 'Revolver', 'Beatles for Sale',
       'Past Masters (Vols. 1 & 2 / Remastered)',
       'On Air – Live at the BBC Volume 2', 'Abbey Road', 'Rubber Soul',
       'Abbey Road (Super Deluxe Edition)', 'Live At The BBC',
       'On Air - Live At The BBC (Vol.2)', "Rock 'n' Roll Music", nan],
      dtype=object)

In [32]:
# how MANY unique values in that series
beatles["Album"].nunique()

23

In [33]:
# the count of each unique value in that series 
beatles["Album"].value_counts()

Album
The Beatles                                34
Live at the BBC                            27
Past Masters (Vols. 1 & 2 / Remastered)    26
Anthology 1                                21
Abbey Road                                 17
Beatles for Sale                           14
Revolver                                   14
With the Beatles                           14
Help!                                      14
Please Please Me                           14
Rubber Soul                                14
A Hard Day's Night                         13
Sgt. Pepper's Lonely Hearts Club Band      13
Let It Be                                  12
Magical Mystery Tour                       11
Anthology 3                                10
Anthology 2                                 5
Yellow Submarine                            4
Live At The BBC                             3
On Air – Live at the BBC Volume 2           1
Abbey Road (Super Deluxe Edition)           1
On Air - Live At The BBC (Vol.2)            1
Rock 'n' Roll Music                         1
Name: count, dtype: int64

## 4. Sort and Count

Pandas has built-in methods for sorting and summarizing data, so you don't need to write any loops. Many more are listed on the [Pandas Cheat Sheet](https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf).

### Sort Values

`sort_values()` sorts by any column. 

The order is **ascending** (alphabetical or numerical) **by default**. Reverse it with `ascending=False`.

In [34]:
# Least danceable songs first
selected_columns = ['Title', 'Album', 'Danceability']
beatles.sort_values("Danceability")[selected_columns]

,Title,Album,Danceability
80,Good Night,The Beatles,0.146
88,Helter Skelter,The Beatles,0.166
184,Only a Northern Song,Yellow Submarine,0.175
197,Revolution 9,The Beatles,0.208
193,Rain,Past Masters (Vols. 1 & 2 / Remastered),0.234
...,...,...,...
16,And I Love Her,A Hard Day's Night,0.767
78,Good Day Sunshine,Revolver,0.770
265,Wild Honey Pie,The Beatles,0.792
179,"Ob-la-di, Ob-la-da",The Beatles,0.818
69,For You Blue,Let It Be,0.880

In [35]:
# Longest songs first (Duration is in seconds)
selected_columns = ['Title', 'Album', 'Duration']       
beatles.sort_values("Duration", ascending=False)[selected_columns].head(10)

,Title,Album,Duration
197,Revolution 9,The Beatles,502.0
111,I Want You (She's So Heavy),Abbey Road,467.0
93,Hey Jude,Past Masters (Vols. 1 & 2 / Remastered),431.0
136,It's All Too Much,Yellow Submarine,388.0
260,What's the New Mary Jane,Anthology 3,372.0
3,A Day in the Life,Sgt. Pepper's Lonely Hearts Club Band,335.0
267,Within You Without You,Sgt. Pepper's Lonely Hearts Club Band,305.0
263,While My Guitar Gently Weeps,The Beatles,286.0
98,I Am the Walrus,Magical Mystery Tour,273.0
88,Helter Skelter,The Beatles,270.0

In [36]:
# The Billboard Top 50, from number 1 down
selected_columns = ['Title', 'Year', 'top_50_billboard']    
beatles.sort_values("top_50_billboard")[selected_columns].head(10)

                        Title  Year  top_50_billboard
93                   Hey Jude  1968               1.0
112  I Want to Hold Your Hand  1963               2.0
209             She Loves You  1963               3.0
72                   Get Back  1969               4.0
146                 Let It Be  1969               5.0
43              Come Together  1969               6.0
86             Hello, Goodbye  1967               7.0
4          A Hard Day's Night  1964               8.0
257        We Can Work It Out  1965               9.0
36          Can't Buy Me Love  1964              10.0

### Count Values

We saw this above, but worth repeating:

`value_counts()` returns the number of entries for each unique value in a column, from most to least frequent.

In [37]:
beatles["Album"].value_counts()

Album
The Beatles                                34
Live at the BBC                            27
Past Masters (Vols. 1 & 2 / Remastered)    26
Anthology 1                                21
Abbey Road                                 17
Beatles for Sale                           14
Revolver                                   14
With the Beatles                           14
Help!                                      14
Please Please Me                           14
Rubber Soul                                14
A Hard Day's Night                         13
Sgt. Pepper's Lonely Hearts Club Band      13
Let It Be                                  12
Magical Mystery Tour                       11
Anthology 3                                10
Anthology 2                                 5
Yellow Submarine                            4
Live At The BBC                             3
On Air – Live at the BBC Volume 2           1
Abbey Road (Super Deluxe Edition)           1
On Air - Live At The BBC (Vol.2)            1
Rock 'n' Roll Music                         1
Name: count, dtype: int64

In [38]:
beatles["lead_vocal"].value_counts()

lead_vocal
Lennon                                                     91
McCartney                                                  73
Harrison                                                   41
McCartney, with Lennon                                     15
Lennon and McCartney                                       14
Lennon, with McCartney                                     14
Starkey                                                    10
Lennon, McCartney and Harrison                              3
Starkey (Best)                                              2
McCartney, with Lennon and Harrison                         1
Lennon, with McCartney and Harrison                         1
Lennon, with Starkey                                        1
Lennon, McCartney, Harrison and Starkey                     1
McCartney, with Lennon, Harrison and Starkey                1
Sheridan                                                    1
Lennon, McCartney, Harrison, Eric Morecambe, Ernie Wise     1
Harrison, with Lennon and McCartney                         1
Lennon, McCartney, Harrison                                 1
Lennon and Harrison                                         1
Name: count, dtype: int64

You may want to store the result of `value_counts()` in a new DataFrame:

In [39]:
album_counts = pd.DataFrame(beatles["Album"].value_counts())
album_counts

                                         count
Album
The Beatles                                 34
Live at the BBC                             27
Past Masters (Vols. 1 & 2 / Remastered)     26
Anthology 1                                 21
Abbey Road                                  17
Beatles for Sale                            14
Revolver                                    14
With the Beatles                            14
Help!                                       14
Please Please Me                            14
Rubber Soul                                 14
A Hard Day's Night                          13
Sgt. Pepper's Lonely Hearts Club Band       13
Let It Be                                   12
Magical Mystery Tour                        11
Anthology 3                                 10
Anthology 2                                  5
Yellow Submarine                             4
Live At The BBC                              3
On Air – Live at the BBC Volume 2            1
Abbey Road (Super Deluxe Edition)            1
On Air - Live At The BBC (Vol.2)             1
Rock 'n' Roll Music                          1

## 5. Combining and Merging DataFrames

When you work with several datasets, you often need to combine them. There are two main ways to do that:

| Operation | When to use |
|-----------|-------------|
| **`pd.concat()`** | Stack DataFrames that share the **same columns** (add more rows) |
| **`pd.merge()`** | Join DataFrames that share a **key column** but have different columns (add new columns) |

**Joining** (`df.join()`) is similar to merging but less versatile, since it combines frames on their index only.

Read more: [concat](https://pandas.pydata.org/docs/reference/api/pandas.concat.html) · [merge](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html) · [join](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.join.html)

### Concatenation vs. Merging

- If your DataFrames have **identical column names**, you *concatenate*.
- If they have different numbers of columns but otherwise share column names, you *might* be able to concatenate, as long as you don't mind lots of missing data in some places.
- If your DataFrames are quite different but **share some common data** (like song titles), you *merge*.

The Beatles CSV in this notebook has *already* been assembled this way: it is the Spotify data merged with the University of Belgrade data. So we don't need to combine anything here. But the syntax is worth knowing for when you have separate sources of your own.

### A Hypothetical Example

Suppose you had two separate DataFrames: `spotify_df` (with a `song` column) and `billboard_df` (with a `Title` column). The general pattern would look like this. *(This is shown for reference only, not run.)*

```python
# Concatenate: stack frames with the same columns
all_songs = pd.concat([songs_part_1, songs_part_2]).reset_index(drop=True)

# Merge: join frames that share a key column
combined = pd.merge(left=billboard_df,
                    right=spotify_df,
                    left_on="Title",
                    right_on="song",
                    how="inner")
```

Key arguments to `pd.merge()`:
- The two frames to be joined are called `left` and `right`.
- `left_on` and `right_on` name the shared column in each frame. The columns don't need the same name, but they must contain the same items (like song titles). If the names *are* the same, you can just write `on="Title"`.
- `how` says which keys to keep. With `"inner"`, only rows with a match in **both** frames are kept. With `"left"`, every row of the left frame is kept, and missing values are filled with `NaN`.
- The optional `suffixes` argument tells Pandas how to label columns that have the same name in both frames.

**One caution:** Pandas only matches keys that are formatted in *exactly* the same way. `"12-Bar Original"` and `"12-bar Original"` count as different songs. So the key columns usually need to be cleaned first.

## 6. Making the Most of Pandas

Pandas is designed so that you almost **never need to write a `for` loop**. There is a built-in method for nearly every common operation on columns and DataFrames, and it applies the operation to the whole column at once.

Before writing custom code, search the [documentation](https://pandas.pydata.org/about/), the [cheat sheet](https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf), or [W3Schools](https://www.w3schools.com/python/pandas/default.asp). Chances are, Pandas already has a built-in way to reach your goal!